# Generated by Django 5.0.4 on 2024-04-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
