# Generated by Django 5.0.6 on 2024-05-16 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_productocategoria_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de actualización'),
        ),
    ]
