# Generated by Django 5.0.6 on 2024-05-16 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0005_pedido_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de actualización'),
        ),
    ]
