# Generated by Django 5.0.6 on 2024-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0007_cliente_direccion_cliente_edad_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
