# Generated by Django 5.0.6 on 2024-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0010_remove_cliente_usuario_cliente_nombre_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
